language: ruby
bundler_args: --without debug
sudo: required
before_install:
  - sudo apt-get install -qq libvips-dev libgsf-1-dev
  - export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
  # - rbx-2 disabled to speed up CI. Renable when needed.
cache: bundler
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0
    - rvm: jruby
